services:
  php:
    build: .
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
      - APP_URL:https://aponscat.com
    ports:
      - "80:8000" # HTTP
      - "443:8000" # HTTPS
      - "443:8000/udp" # HTTP/3
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - .:/app
    restart: always

# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config:
  app: